using Godot;
using Hollowdeck.Combat;
using Hollowdeck.Data;
using Hollowdeck.Map;

namespace Hollowdeck.UI;

// Convention-based art lookup: assets are named by definition id
// (assets/icons/cards/<card_id>.png, assets/sprites/enemies/<enemy_id>.png),
// so new content picks up art by dropping in a matching file - no schema or
// code change. Missing art returns null and views degrade to text-only.
//
// Every path here is a .png. The icons were SVG until Phase 3 and are now
// generated by tools/artgen against the same ids - the convention is what let
// 78 files change medium without touching this file beyond the extension.
public static class ArtAssets
{
    // Upgraded cards (CardUpgrade.Apply appends "+" to the id) reuse their
    // base card's art - there's no separate "strike+.png" asset.
    public static Texture2D? CardIcon(string cardId) => Load($"res://assets/icons/cards/{cardId.TrimEnd('+')}.png");
    public static Texture2D? RelicIcon(string relicId) => Load($"res://assets/icons/relics/{relicId}.png");
    public static Texture2D? PotionIcon(string potionId) => Load($"res://assets/icons/potions/{potionId}.png");
    public static Texture2D? EnemySprite(string enemyId) => Load($"res://assets/sprites/enemies/{enemyId}.png");
    public static Texture2D? PlayerSprite() => Load("res://assets/sprites/player.png");

    public static Texture2D? MapIcon(MapNodeType type) => Load($"res://assets/icons/map/{type switch
    {
        MapNodeType.Combat => "fight",
        MapNodeType.Elite => "elite",
        MapNodeType.Rest => "rest",
        MapNodeType.Shop => "shop",
        MapNodeType.Treasure => "treasure",
        MapNodeType.Boss => "boss",
        MapNodeType.Event => "event",
        _ => "unknown",
    }}.png");

    public static Texture2D? IntentIcon(IntentType type) => Load($"res://assets/icons/intents/{type switch
    {
        IntentType.Attack => "attack",
        IntentType.Defend => "defend",
        IntentType.Buff => "buff",
        IntentType.Debuff => "debuff",
        IntentType.Summon => "summon",
        IntentType.Escape => "escape",
        _ => "unknown",
    }}.png");

    public static Texture2D? StatusIcon(StatusType type) =>
        Load($"res://assets/icons/status/{type.ToString().ToLowerInvariant()}.png");

    // Per-event illustration, falling back to the map's scroll. The fallback
    // is the point: a new event authored in events.json gets a screen that
    // still looks finished, and picks up bespoke art the moment a matching
    // file appears - same convention as everything above, but this is the one
    // lookup where "no art" is an expected state rather than a bug.
    public static Texture2D? EventIcon(string eventId) =>
        Load($"res://assets/icons/events/{eventId}.png") ?? MapIcon(MapNodeType.Event);

    public static Texture2D? BackgroundTile(string name) => Load($"res://assets/backgrounds/{name}.png");

    private static Texture2D? Load(string path) =>
        ResourceLoader.Exists(path) ? GD.Load<Texture2D>(path) : null;
}
