using System.Collections.Generic;
using Godot;
using Hollowdeck.Combat;
using Hollowdeck.Data;
using Hollowdeck.Map;

namespace Hollowdeck.UI;

// Convention-based art lookup: assets are named by definition id
// (assets/icons/cards/<card_id>.png, assets/sprites/enemies/<enemy_id>.png),
// so new content picks up art by dropping in a matching file - no schema or
// code change. Missing art returns null and views degrade to text-only.
//
// Every path here is a .png. The icons were SVG until Phase 3 and are now
// generated by tools/artgen against the same ids - the convention is what let
// 78 files change medium without touching this file beyond the extension.
public static class ArtAssets
{
    // Upgraded cards (CardUpgrade.Apply appends "+" to the id) reuse their
    // base card's art - there's no separate "strike+.png" asset.
    public static Texture2D? CardIcon(string cardId) => Load($"res://assets/icons/cards/{cardId.TrimEnd('+')}.png");
    public static Texture2D? RelicIcon(string relicId) => Load($"res://assets/icons/relics/{relicId}.png");
    public static Texture2D? PotionIcon(string potionId) => Load($"res://assets/icons/potions/{potionId}.png");
    public static Texture2D? EnemySprite(string enemyId) => Load($"res://assets/sprites/enemies/{enemyId}.png");
    public static Texture2D? PlayerSprite() => Load("res://assets/sprites/player.png");

    // The derived animation frames tools/artgen writes beside the sourced
    // roster (see tools/artgen/src/anim.rs). Loads until the first gap, so the
    // frame count lives on disk rather than being restated here - anim.rs owns
    // it, and PixelSpecSmokeTest asserts the two agree.
    //
    // Deliberately no fallback to the static sprite, unlike EventIcon: art
    // that is *generated* for every id is missing only because `artgen animate`
    // was not re-run, and a silent fallback would make that indistinguishable
    // from working. Callers get an empty array and the smoke test fails.
    public static Texture2D[] AnimFrames(string spriteId, string clip)
    {
        var frames = new List<Texture2D>();
        for (int i = 0; ; i++)
        {
            var texture = Load($"res://assets/sprites/anim/{spriteId}/{clip}_{i}.png");
            if (texture is null) break;
            frames.Add(texture);
        }
        return frames.ToArray();
    }

    public static Texture2D? MapIcon(MapNodeType type) => Load($"res://assets/icons/map/{type switch
    {
        MapNodeType.Combat => "fight",
        MapNodeType.Elite => "elite",
        MapNodeType.Rest => "rest",
        MapNodeType.Shop => "shop",
        MapNodeType.Treasure => "treasure",
        MapNodeType.Boss => "boss",
        MapNodeType.Event => "event",
        _ => "unknown",
    }}.png");

    // The "?" a concealed map node draws instead of its real type. Deliberately
    // the same file MapIcon falls back to: the glyph is drawn as "the ? of an
    // unresolved node type" (tools/artgen/src/icons/misc.rs) and that is
    // exactly what this is. PixelSpecSmokeTest's two map sweeps are unaffected
    // - the coverage one drives MapIcon over enum members, and the orphan one
    // already exempts `unknown` - so this is not a way of smuggling a missing
    // switch arm past them.
    public static Texture2D? ConcealedMapIcon() => Load("res://assets/icons/map/unknown.png");

    public static Texture2D? IntentIcon(IntentType type) => Load($"res://assets/icons/intents/{type switch
    {
        IntentType.Attack => "attack",
        IntentType.Defend => "defend",
        IntentType.Buff => "buff",
        IntentType.Debuff => "debuff",
        IntentType.Summon => "summon",
        IntentType.Escape => "escape",
        IntentType.Dormant => "dormant",
        _ => "unknown",
    }}.png");

    public static Texture2D? StatusIcon(StatusType type) =>
        Load($"res://assets/icons/status/{type.ToString().ToLowerInvariant()}.png");

    // Per-event illustration, falling back to the map's scroll. The fallback
    // is the point: a new event authored in events.json gets a screen that
    // still looks finished, and picks up bespoke art the moment a matching
    // file appears - same convention as everything above, but this is the one
    // lookup where "no art" is an expected state rather than a bug.
    public static Texture2D? EventIcon(string eventId) =>
        Load($"res://assets/icons/events/{eventId}.png") ?? MapIcon(MapNodeType.Event);

    public static Texture2D? BackgroundTile(string name) => Load($"res://assets/backgrounds/{name}.png");

    private static Texture2D? Load(string path) =>
        ResourceLoader.Exists(path) ? GD.Load<Texture2D>(path) : null;
}
