using Godot;

namespace Hollowdeck.UI;

// The combat effect frames - docs/PIXEL_ART_ROADMAP.md section 5.
//
// Six generated four-frame runs (tools/artgen/src/icons/fx.rs), spawned as a
// transient TextureRect and played one-shot by SpriteAnimator. Four of them
// burst in place; the other two travel, which is the whole of how a slash gets
// a direction without an authored direction set (see PlayTravelling). Those two
// are one blade in two pigments and share a single drawn axis, because an axis
// is undirected - see Gash. What they replaced was CombatScreen.SpawnHitSpark:
// a CpuParticles2D burst whose texture was a 24x24 radial GradientTexture2D
// drawn at ScaleAmountMin 0.4 / Max 0.9.
//
// That was off the medium in three separate ways - a smooth gradient against
// ART_SPEC section 5's 43-colour ramp, a soft alpha edge against section 3, and
// a fractional scale against section 2 - and **nothing in the project could see
// any of it**. PixelSpecSmokeTest's transform scan only knows identifiers
// declared TextureRect, and a CpuParticles2D is not one; `artgen validate`
// reads files under assets/, and a texture built in a C# constructor is not
// one. It was the last smooth-gradient art on the combat screen and it survived
// every check the pixel passes added, which is the argument for this file
// existing rather than for tightening the spark.
//
// Where the art lives is the one surprising thing: assets/icons/fx/, not
// assets/sprites/. These are frame runs and the sprites tree is where frame
// runs are, so the naming reads backwards - but assets/icons is a directory
// `artgen`'s output_dir already routes to with no arm, and one CI already diffs
// for drift. A new output directory costs a line in output_dir *and* a line in
// that step's path list, and the second of those two lines is exactly what was
// missed when chrome landed: fourteen slices were regenerated by CI and then
// ignored for as long as chrome existed. Paying nothing was worth the odd name.
public static class CombatFx
{
    // A hit that took HP. Fires from PlayHitVfx on both the player and an enemy.
    public const string Impact = "impact";

    // A hit Block absorbed whole - the beat PlayBlockAbsorbVfx already had.
    public const string Ward = "ward";

    // A heal. Previously a green FloatingText and nothing else.
    public const string Bloom = "bloom";

    // Poison landing on a target. Previously nothing at all: the only sign was
    // the status row redrawing a turn's worth of information at once.
    public const string Venom = "venom";

    // The player's blade reaching an enemy. The first of the two effects that
    // travel, and one of the two whose subject is the attack rather than its
    // result - so it is drawn in bone rather than in any of the six chromatic
    // families the bursts use.
    public const string Swipe = "swipe";

    // The same blade coming the other way: an enemy's attack reaching the
    // player. Oxblood rather than bone, and the pigment is the *whole* of the
    // difference - fx.rs draws it by calling swipe()'s own geometry with other
    // colours.
    //
    // PIXEL_ART_ROADMAP section 5 forecast that this "would be an authored
    // second orientation rather than a reuse", which is that section's second
    // wrong forecast about this effect and wrong the same way. An axis is
    // undirected: the player's attack vector spans about -13 to -49 degrees and
    // an enemy's spans 131 to 167, which is the same line read from the other
    // end, and every swipe frame is symmetric under a half turn. There was
    // nothing to reorient. What an incoming blade needed was a colour, so it
    // does not read as the player swinging at themselves.
    //
    // R is the family `impact` declined - "Ember rather than oxblood: R5 is the
    // damage *number*" - which is exactly what recommends it here. This is the
    // colour of the number about to land on the player's own HP bar.
    //
    // Spelled `gash` rather than `rend` because rot_hound already has a move
    // called rend; fx.rs's own naming rule is that an asset name reading as a
    // definition id makes a grep ambiguous about which one is meant.
    public const string Gash = "gash";

    // Every effect, for the coverage check. The list is what
    // PixelSpecSmokeTest drives rather than a set of names retyped there, so a
    // sixth effect is registered in one place - the third-copy failure
    // SpriteAnimator.CreatureClips is the same fix for.
    public static readonly string[] All = { Impact, Ward, Bloom, Venom, Swipe, Gash };

    // Seconds per frame. Four frames at this cadence is 0.24s, which sits
    // between the hit clip's 0.10 and the enemy turn's 0.35 pacing - long
    // enough to read as a beat, short enough that two hits in one card's
    // resolution do not queue up visibly.
    //
    // One number for all four bursts rather than a table keyed by effect: they
    // are the same shape in four pigments (see fx.rs), so a per-effect dial
    // would be a content knob for a difference that does not exist. The two
    // blades are the same argument again and share TravelFrameSeconds below.
    public const double FrameSeconds = 0.06;

    // And a second number for the two runs that travel, which is *not* the
    // per-effect dial the paragraph above declines.
    //
    // For a stationary burst the cadence decides only how long the beat lasts.
    // For a travelling one it also decides how fast the thing crosses the
    // screen, because the tween is fitted to the run - so the two are
    // different kinds of number and collapsing them would mean choosing a
    // slash speed by editing every burst's duration.
    //
    // 0.04 puts a blade's whole run at 0.16s against Impact's 0.24s, and
    // TravelFraction lands it on the target at the drawn-edge frame so its
    // tail and motes dissipate *on* the enemy. Both matter: the two are
    // spawned in the same frame by PlayHitVfx, and a blade still in flight
    // while the impact blooms under it reads as the hit landing before the
    // weapon arrived.
    public const double TravelFrameSeconds = 0.04;
    public const double TravelFraction = 0.5;

    /// <summary>
    /// Spawns <paramref name="effect"/> centred on <paramref name="localCenter"/>
    /// in <paramref name="parent"/>'s coordinates. The node frees itself when
    /// the run ends.
    /// </summary>
    public static void Play(Node parent, Vector2 localCenter, string effect)
    {
        if (Spawn(parent, localCenter, effect) is not { } spawned) return;
        SpriteAnimator.AttachOneShot(spawned.Rect, spawned.Frames, FrameSeconds, spawned.Rect.QueueFree);
    }

    /// <summary>
    /// Spawns <paramref name="effect"/> at <paramref name="fromLocal"/> and carries it
    /// to <paramref name="toLocal"/> while its frames run, both in
    /// <paramref name="parent"/>'s coordinates. The node frees itself when the run ends.
    /// </summary>
    // Direction comes from the motion, which is why the art is one orientation
    // rather than the eight-way set PIXEL_ART_ROADMAP section 5 forecast. That
    // forecast read "a streak spans player->enemy at an arbitrary angle", and
    // the angle is not arbitrary: PlayerSprite is pinned at canvas (120, 350)
    // and every target is an EnemyView centre inside EnemyRow, so across one to
    // four enemies the vector only ever spans about -13 to -49 degrees. Eight
    // authored images, two of them ever seen.
    //
    // One orientation covers the *return* trip too, which is the same section's
    // second wrong forecast. An enemy's vector spans 131 to 167 degrees, which
    // is the identical undirected line, and fx.rs asserts every axial frame is
    // symmetric under a half turn. So both blades are spawned through here and
    // differ only in which frames the caller names.
    //
    // Tweening `position` is legal where tweening `scale` is not, and the
    // distinction is section 9's rather than an oversight in the guard: a
    // transform resamples the texture, a translation onto a whole source pixel
    // does not. Both endpoints go through SnapTranslation for that reason, and
    // PlayPlayerPositionBeat already animates _playerSprite exactly this way.
    //
    // Ungated on ReduceMotion, like the lunge and the hit shake beside it. The
    // opening flash frame is declined anyway - AttachOneShot does it for every
    // run in this file through SpriteAnimator.FlashOpeningClips - and what is
    // left is moment-to-moment combat juice, which ROADMAP Phase 11's
    // animation-speed setting is the answer to rather than this binary.
    public static void PlayTravelling(Node parent, Vector2 fromLocal, Vector2 toLocal, string effect)
    {
        if (Spawn(parent, fromLocal, effect) is not { } spawned) return;

        var rect = spawned.Rect;
        double run = TravelFrameSeconds * spawned.Frames.Length;
        SpriteAnimator.AttachOneShot(rect, spawned.Frames, TravelFrameSeconds, rect.QueueFree);

        var landing = PixelSpec.SnapTranslation(toLocal - rect.Size / 2f, PixelSpec.SpriteScale);
        // Motion.Jolt is the vocabulary's only Linear curve, and a blade that
        // eased into its target would be decelerating through the body. Its
        // table row is about a shake step because that was the only linear
        // thing in the game when section 11 was written; the shape is what is
        // being reused, and MotionCurve.Over is the sanctioned way to take it
        // at another period.
        rect.CreateTween().TweenTo(rect, "position", landing, Motion.Jolt.Over((float)(run * TravelFraction)));
    }

    // The half Play and PlayTravelling share: resolve the frames, build the
    // rect, put it on a whole source pixel. Split out when the second entry
    // point arrived rather than copied, because the snap is the part that is
    // easy to leave off and impossible to see afterwards.
    private static (TextureRect Rect, Texture2D[] Frames)? Spawn(Node parent, Vector2 localCenter, string effect)
    {
        var frames = ArtAssets.FxFrames(effect);
        if (frames.Length == 0)
        {
            // Named rather than silent, the DataFile.cs argument. An effect
            // that does not spawn is indistinguishable from one nothing called,
            // and this is the arm a forgotten `artgen generate` lands on.
            GD.PushError($"CombatFx: no frames for '{effect}' - run `artgen generate fx` and re-import");
            return null;
        }

        var rect = new TextureRect
        {
            Texture = frames[0],
            // A 160x160 Control laid over the enemy row would swallow clicks on
            // the enemy underneath it, which is a live targeting bug rather
            // than a cosmetic one. The CpuParticles2D this replaces was a
            // Node2D and could never have done that, so the hazard arrives with
            // the fix.
            MouseFilter = Control.MouseFilterEnum.Ignore,
        };
        // Nearest filter, an exact 32 -> 160 box, and KeepAspectCentered, in the
        // one call every pixel TextureRect in the project uses.
        PixelSpec.ApplyPixelRect(rect, PixelSpec.CreatureGrid, PixelSpec.SpriteScale);
        rect.Size = rect.CustomMinimumSize;

        // The centre comes from a Control's GlobalPosition plus half its Size,
        // so it is fractional far more often than not. Section 9 wants a pixel
        // asset to sit on a whole source pixel; snapping the top-left is what
        // that means for a node placed rather than tweened.
        rect.Position = PixelSpec.SnapTranslation(localCenter - rect.Size / 2f, PixelSpec.SpriteScale);

        parent.AddChild(rect);
        return (rect, frames);
    }
}
