using Godot;

namespace Hollowdeck.UI;

// The combat effect bursts - docs/PIXEL_ART_ROADMAP.md section 5.
//
// Four generated four-frame runs (tools/artgen/src/icons/fx.rs), spawned as a
// transient TextureRect and played one-shot by SpriteAnimator. What they
// replaced was CombatScreen.SpawnHitSpark: a CpuParticles2D burst whose texture
// was a 24x24 radial GradientTexture2D drawn at ScaleAmountMin 0.4 / Max 0.9.
//
// That was off the medium in three separate ways - a smooth gradient against
// ART_SPEC section 5's 43-colour ramp, a soft alpha edge against section 3, and
// a fractional scale against section 2 - and **nothing in the project could see
// any of it**. PixelSpecSmokeTest's transform scan only knows identifiers
// declared TextureRect, and a CpuParticles2D is not one; `artgen validate`
// reads files under assets/, and a texture built in a C# constructor is not
// one. It was the last smooth-gradient art on the combat screen and it survived
// every check the pixel passes added, which is the argument for this file
// existing rather than for tightening the spark.
//
// Where the art lives is the one surprising thing: assets/icons/fx/, not
// assets/sprites/. These are frame runs and the sprites tree is where frame
// runs are, so the naming reads backwards - but assets/icons is a directory
// `artgen`'s output_dir already routes to with no arm, and one CI already diffs
// for drift. A new output directory costs a line in output_dir *and* a line in
// that step's path list, and the second of those two lines is exactly what was
// missed when chrome landed: fourteen slices were regenerated by CI and then
// ignored for as long as chrome existed. Paying nothing was worth the odd name.
public static class CombatFx
{
    // A hit that took HP. Fires from PlayHitVfx on both the player and an enemy.
    public const string Impact = "impact";

    // A hit Block absorbed whole - the beat PlayBlockAbsorbVfx already had.
    public const string Ward = "ward";

    // A heal. Previously a green FloatingText and nothing else.
    public const string Bloom = "bloom";

    // Poison landing on a target. Previously nothing at all: the only sign was
    // the status row redrawing a turn's worth of information at once.
    public const string Venom = "venom";

    // Every effect, for the coverage check. The list is what
    // PixelSpecSmokeTest drives rather than a set of names retyped there, so a
    // fifth burst is registered in one place - the third-copy failure
    // SpriteAnimator.CreatureClips is the same fix for.
    public static readonly string[] All = { Impact, Ward, Bloom, Venom };

    // Seconds per frame. Four frames at this cadence is 0.24s, which sits
    // between the hit clip's 0.10 and the enemy turn's 0.35 pacing - long
    // enough to read as a beat, short enough that two hits in one card's
    // resolution do not queue up visibly.
    //
    // One number for all four rather than a table keyed by effect: these are
    // the same shape in four pigments (see fx.rs), so a per-effect dial would
    // be a content knob for a difference that does not exist.
    public const double FrameSeconds = 0.06;

    /// <summary>
    /// Spawns <paramref name="effect"/> centred on <paramref name="localCenter"/>
    /// in <paramref name="parent"/>'s coordinates. The node frees itself when
    /// the run ends.
    /// </summary>
    public static void Play(Node parent, Vector2 localCenter, string effect)
    {
        var frames = ArtAssets.FxFrames(effect);
        if (frames.Length == 0)
        {
            // Named rather than silent, the DataFile.cs argument. An effect
            // that does not spawn is indistinguishable from one nothing called,
            // and this is the arm a forgotten `artgen generate` lands on.
            GD.PushError($"CombatFx: no frames for '{effect}' - run `artgen generate fx` and re-import");
            return;
        }

        var rect = new TextureRect
        {
            Texture = frames[0],
            // A 160x160 Control laid over the enemy row would swallow clicks on
            // the enemy underneath it, which is a live targeting bug rather
            // than a cosmetic one. The CpuParticles2D this replaces was a
            // Node2D and could never have done that, so the hazard arrives with
            // the fix.
            MouseFilter = Control.MouseFilterEnum.Ignore,
        };
        // Nearest filter, an exact 32 -> 160 box, and KeepAspectCentered, in the
        // one call every pixel TextureRect in the project uses.
        PixelSpec.ApplyPixelRect(rect, PixelSpec.CreatureGrid, PixelSpec.SpriteScale);
        rect.Size = rect.CustomMinimumSize;

        // The centre comes from a Control's GlobalPosition plus half its Size,
        // so it is fractional far more often than not. Section 9 wants a pixel
        // asset to sit on a whole source pixel; snapping the top-left is what
        // that means for a node placed rather than tweened.
        rect.Position = PixelSpec.SnapTranslation(localCenter - rect.Size / 2f, PixelSpec.SpriteScale);

        parent.AddChild(rect);
        SpriteAnimator.AttachOneShot(rect, frames, FrameSeconds, rect.QueueFree);
    }
}
